version: '3'
services:
  app:
    container_name: app
    build: 
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"
    depends_on:    
      - db
    links:
      - db 
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/restapi_script ,restapi_test
    networks:
      - enrollment
    
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=restapi_script
      # - POSTGRES_DB=restapi_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - enrollment  

  #  volumes:
   #   - db-data:/var/lib/postgresql/data2

volumes:
  db-data:

networks:
  enrollment:
    driver: bridge   


#   psql -U  user -d restapi_script && \l
#  psql -u  user -d restapi_script \dt