version: '3.9'
services:
  app:
    container_name: app
    depends_on:    
      - db
    build: 
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"

    links:
      - db 
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/restapi_script
    networks:
      - enrollment
    
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=restapi_script   
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - enrollment  

    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d #либо для теста создавать 2 контейнер с БД
   #   - db-data:/var/lib/postgresql/data2 # Для хранения БД на локальной машине

volumes:
  db-data:

#не обязательно
networks:
  enrollment:
    driver: bridge   


# psql -U  user -d restapi_script -c "CREATE DATABASE restapi_test;"
# psql -U user -d restapi_test -c "CREATE TABLE commandsdb (id SERIAL PRIMARY KEY, script TEXT, result TEXT);"
# // psql -U user -d restapi_script -c "SELECT * FROM commandsdb;"
# docker-compose build