env: "local" #local, dev, prod 
# storage_path: "./storage/storage.db" #storage path
# database_url: "host=localhost dbname=restapi_script sslmode=disable"
storage_path: "host=localhost dbname=restapi_script sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 4s 
  idle_timeout: 1m 