env: "local" #local, dev, prod 


namebase: "restapi_script"
flags: "sslmode=disable"
databaseURL: "host=localhost dbname=restapi_script  sslmode=disable"
http_server:
  address: ":8080"
  timeout: 4s 
  idle_timeout: 1m 