env: "local" #local, dev, prod 

# Для докера
# databaseURL: "host=db dbname=restapi_script  sslmode=disable user=user password=password"

# Для запуска через Makefile
# databaseURL:= fmt.Sprintf("host=%s dbname=restapi_script sslmode=disable", os.Getenv("DATABASE_HOST"))
authbase: "user:password"
namebase: "restapi_script"
flags: "sslmode=disable"
databaseURL: "host=localhost dbname=restapi_script  sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 4s 
  idle_timeout: 1m 